name: Release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Display Go version
        run: go version

      - run: |
          mkdir -p output
          go get github.com/go-delve/delve/cmd/dlv

      - name: Build For Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -v -o output/fgor-windows-amd64.exe github.com/jc-lab/fully-go-remote/cmd
          GOOS=windows GOARCH=amd64 go build -v -o output/dlv-windows-amd64.exe github.com/go-delve/delve/cmd/dlv
      - name: Build For Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o output/fgor-linux-amd64 github.com/jc-lab/fully-go-remote/cmd
          GOOS=linux GOARCH=amd64 go build -v -o output/dlv-linux-amd64 github.com/go-delve/delve/cmd/dlv
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            output/*
